# Label Configuration for Recipe Admin UI Service
# Enhanced label strategy for comprehensive issue and PR management

# Core Type Labels
- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"

- name: 'enhancement'
  color: 'a2eeef'
  description: 'New feature or request'

- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'performance'
  color: 'f9d0c4'
  description: 'Performance improvements'

- name: 'security'
  color: 'b60205'
  description: 'Security-related issues'

- name: 'refactor'
  color: 'fbca04'
  description: 'Code refactoring'

# Priority Labels
- name: 'priority: critical'
  color: 'b60205'
  description: 'Critical priority - requires immediate attention'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority'

- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority'

# Status Labels
- name: 'needs-triage'
  color: 'ededed'
  description: 'Needs initial review and triage'

- name: 'needs-reproduction'
  color: 'fef2c0'
  description: 'Cannot reproduce issue'

- name: 'needs-info'
  color: 'd876e3'
  description: 'More information needed'

- name: 'in-progress'
  color: '0052cc'
  description: 'Work in progress'

- name: 'blocked'
  color: 'b60205'
  description: 'Blocked by external dependency'

- name: 'stale'
  color: 'ededed'
  description: 'No recent activity'

- name: 'wont-fix'
  color: 'ffffff'
  description: 'Will not be fixed'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'Duplicate of another issue'

# Component Labels
- name: 'authentication'
  color: '5319e7'
  description: 'Authentication/login related'

- name: 'api'
  color: '1d76db'
  description: 'API integration'

- name: 'ui'
  color: 'c5def5'
  description: 'User interface'

- name: 'core'
  color: 'bfdadc'
  description: 'Core functionality'

- name: 'shared'
  color: 'c2e0c6'
  description: 'Shared components/utilities'

- name: 'features'
  color: 'd4c5f9'
  description: 'Feature modules'

- name: 'layout'
  color: 'e99695'
  description: 'Layout components'

- name: 'testing'
  color: '0e8a16'
  description: 'Testing related'

- name: 'tests'
  color: '1f7a1f'
  description: 'Test changes'

# Tech Stack Labels
- name: 'angular'
  color: 'dd0031'
  description: 'Angular framework'

- name: 'typescript'
  color: '3178c6'
  description: 'TypeScript language'

- name: 'javascript'
  color: 'f1e05a'
  description: 'JavaScript'

- name: 'html'
  color: 'e34c26'
  description: 'HTML templates'

- name: 'styles'
  color: '563d7c'
  description: 'CSS/SCSS/Styling'

- name: 'docker'
  color: '0db7ed'
  description: 'Docker related'

- name: 'kubernetes'
  color: '326ce5'
  description: 'Kubernetes deployment'

# Special Labels
- name: 'good-first-issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help-wanted'
  color: '008672'
  description: 'Extra attention needed'

- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates'

- name: 'github-actions'
  color: '2088ff'
  description: 'GitHub Actions workflows'

- name: 'github'
  color: 'fbca04'
  description: 'GitHub configuration'

- name: 'breaking-change'
  color: 'd73a4a'
  description: 'Contains breaking changes'

- name: 'pinned'
  color: 'fef2c0'
  description: "Pinned issue - won't go stale"

- name: 'work-in-progress'
  color: 'fbca04'
  description: 'Work in progress - do not merge'

# Area Labels
- name: 'build-tools'
  color: 'bfd4f2'
  description: 'Build tools and configuration'

- name: 'linting'
  color: 'd1f0fd'
  description: 'Linting and code quality'

- name: 'configuration'
  color: 'c5def5'
  description: 'Configuration files'

- name: 'accessibility'
  color: '0e8a16'
  description: 'Accessibility improvements'

- name: 'mobile'
  color: '5319e7'
  description: 'Mobile/responsive design'

- name: 'ssr'
  color: '1d76db'
  description: 'Server-side rendering'

# Discussion Labels
- name: 'idea'
  color: 'a2eeef'
  description: 'New idea or suggestion'

- name: 'question'
  color: 'd876e3'
  description: 'Further information requested'

- name: 'show-and-tell'
  color: '0e8a16'
  description: 'Community showcase'
