- name: 'bug'
  color: 'd73a4a'
  description: "Something isn't working"

- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or pull request already exists'

- name: 'enhancement'
  color: 'a2eeef'
  description: 'New feature or request'

- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'

- name: 'invalid'
  color: 'e4e669'
  description: "This doesn't seem right"

- name: 'question'
  color: 'd876e3'
  description: 'Further information is requested'

- name: 'wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

# Priority labels
- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority issue'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority issue'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority issue'

- name: 'priority: critical'
  color: 'b60205'
  description: 'Critical priority issue'

# Type labels
- name: 'type: feature'
  color: '1d76db'
  description: 'New feature implementation'

- name: 'type: bugfix'
  color: 'ee0701'
  description: 'Bug fix'

- name: 'type: improvement'
  color: '5319e7'
  description: 'Enhancement to existing functionality'

- name: 'type: refactor'
  color: 'e99695'
  description: 'Code refactoring'

- name: 'type: security'
  color: 'b60205'
  description: 'Security related issue'

- name: 'type: performance'
  color: '0052cc'
  description: 'Performance improvement'

- name: 'type: test'
  color: '1f7a1f'
  description: 'Testing related changes'

- name: 'type: ci'
  color: '006b75'
  description: 'CI/CD related changes'

- name: 'type: dependencies'
  color: '0366d6'
  description: 'Dependency updates'

# Area labels
- name: 'area: frontend'
  color: 'c2e0c6'
  description: 'Frontend/UI related'

- name: 'area: backend'
  color: 'fef2c0'
  description: 'Backend/API related'

- name: 'area: auth'
  color: 'f9d0c4'
  description: 'Authentication and authorization'

- name: 'area: build'
  color: 'd4c5f9'
  description: 'Build system and tooling'

- name: 'area: docs'
  color: 'c5def5'
  description: 'Documentation related'

# Status labels
- name: 'status: needs review'
  color: 'fbca04'
  description: 'Awaiting code review'

- name: 'status: needs testing'
  color: '0e8a16'
  description: 'Needs testing before merge'

- name: 'status: blocked'
  color: 'd93f0b'
  description: 'Blocked by another issue or dependency'

- name: 'status: in progress'
  color: '0052cc'
  description: 'Currently being worked on'

- name: 'status: ready'
  color: '0e8a16'
  description: 'Ready to be worked on'

# Special labels
- name: 'breaking change'
  color: 'b60205'
  description: 'Introduces breaking changes'

- name: 'needs design'
  color: 'e99695'
  description: 'Needs design input'

- name: 'dependencies'
  color: '0366d6'
  description: 'Pull requests that update a dependency file'
