extends:
  - recommended

rules:
  info-contact: warn
  info-license: warn
  operation-operationId: error
  operation-description: warn
  tag-description: off
  no-empty-servers: error
  no-unused-components: off
  operation-4xx-response: off

apis:
  main:
    root: docs/api/openapi.yaml
