labels: ['question']

body:
  - type: markdown
    attributes:
      value: |
        Ask questions about using the admin UI service!

        💡 **Tip**: Search existing discussions first to see if your question has been answered.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What is your question about?
      options:
        - Getting Started/Setup
        - Authentication/Authorization
        - Angular/TypeScript
        - UI/Styling/Theming
        - API Integration
        - Configuration
        - Testing
        - Deployment
        - Performance
        - Best Practices
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you already tried? What's your setup?
      placeholder: |
        I'm trying to...
        I've already tried...
        My setup includes...
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Relevant Configuration
      description: Share relevant configuration or code snippets
      render: typescript
      placeholder: |
        // Your configuration or code here
    validations:
      required: false
