---
# k8s/secret-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: admin-ui-secrets
  namespace: admin-ui
  labels:
    app: admin-ui-service
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret-value" | base64

  # OAuth2 Client Secret
  OAUTH2_CLIENT_SECRET: '${OAUTH2_CLIENT_SECRET_B64}'

  # JWT Secret (for token validation when introspection is disabled)
  # Only used if OAUTH2_INTROSPECTION_ENABLED=false
  JWT_SECRET: '${JWT_SECRET_B64}'
