name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: '[Feature] '
labels: ['enhancement', 'needs-triage']
assignees:
  - jsamuelsen

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when... / Users need to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the desired functionality and user experience
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or approaches have you considered?
      placeholder: Describe alternative implementations or workarounds
    validations:
      required: false

  - type: dropdown
    id: component-area
    attributes:
      label: Component/Area
      description: Which part of the application would this affect?
      options:
        - Authentication/Login
        - User Management
        - Recipe Management
        - Dashboard/Home
        - Settings/Configuration
        - Navigation/Routing
        - API Integration
        - Theming/UI
        - Search/Filtering
        - Forms/Validation
        - Notifications
        - Performance
        - Accessibility
        - Mobile/Responsive
        - SSR
        - Build/Tooling
        - Other
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low (nice to have)
        - Medium (would improve UX)
        - High (important for users)
        - Critical (blocking functionality)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or user story
      placeholder: |
        As a [user type]
        I want to [action]
        So that I can [benefit]
    validations:
      required: true

  - type: textarea
    id: ui-ux-design
    attributes:
      label: UI/UX Design Ideas
      description: Mock-ups, wireframes, or design suggestions
      placeholder: |
        - Add button to...
        - Modal should display...
        - Layout could be...
        - Include screenshots or links to designs
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature would NOT introduce breaking changes
          required: false
        - label: This feature MIGHT introduce breaking changes
          required: false

  - type: checkboxes
    id: security-implications
    attributes:
      label: Security Implications
      description: Are there security considerations?
      options:
        - label: This feature has no security implications
          required: false
        - label: This feature requires security review
          required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] User can perform X action
        - [ ] System responds with Y
        - [ ] Edge case Z is handled
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, examples from other apps
      placeholder: Any additional information

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
