name: Greet Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time issue creator
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.issue.user.login;

            // Check if this is the user's first issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: creator,
              state: 'all'
            });

            if (issues.data.length === 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: `👋 Hello @${creator}!

            Thank you for opening your first issue in the Recipe Web App admin-ui-service repository!
            We appreciate you taking the time to contribute.

            A maintainer will review your issue and respond as soon as possible.

            **In the meantime, please make sure you've:**
            - [ ] Provided all the requested information
            - [ ] Searched for similar existing issues
            - [ ] Read our [Contributing Guidelines](.github/CONTRIBUTING.md)
            - [ ] Reviewed our [Code of Conduct](.github/CODE_OF_CONDUCT.md)

            **Helpful Resources:**
            - [Project Documentation](../README.md)
            - [Technical Specification](../TECHNICAL_SPEC.md)
            - [Support Guide](.github/SUPPORT.md)

            Welcome to the Recipe Web App community! 🎉`
              });
            }

      - name: Greet first-time PR creator
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v7
        with:
          script: |
            const creator = context.payload.pull_request.user.login;

            // Check if this is the user's first PR
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              creator: creator
            });

            if (prs.data.length === 1) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: `🎉 Congratulations @${creator} on opening your first pull request in the admin-ui-service!

            Thank you for taking the time to contribute to the Recipe Web App! We're excited to review your changes.

            **What happens next?**
            - Automated checks will run on your PR
            - A maintainer will review your code and provide feedback
            - Please address any comments or suggestions
            - Once approved, a maintainer will merge your PR

            **Angular/Frontend-specific tips:**
            - Run \`npm run lint\` before committing
            - Ensure \`npm test\` passes locally
            - Run \`npm run format:check\` for code formatting
            - Test both client-side and SSR rendering if applicable
            - Verify browser compatibility if UI changes are included

            **Helpful resources:**
            - [Contributing Guidelines](.github/CONTRIBUTING.md)
            - [Code of Conduct](.github/CODE_OF_CONDUCT.md)
            - [Pull Request Template](.github/pull_request_template.md)
            - [Technical Specification](../TECHNICAL_SPEC.md)

            Thank you for being part of our community! 🙌`
              });
            }
